# Generated by Django 4.2.4 on 2023-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_remove_clip_object_id_clip_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='uuid',
            field=models.CharField(default='67c1522509a240f08a85e3055403c8b1', max_length=200, unique=True),
        ),
    ]
