# Generated by Django 4.2.4 on 2023-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_alter_clip_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('HIDDEN', 'Hidden'), ('PRIVATE', 'Private')], default='HIDDEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='clip',
            name='uuid',
            field=models.CharField(default='0fbb06b7e06a4f57903bc73659a16d03', max_length=200, unique=True),
        ),
    ]
