# Generated by Django 4.2.4 on 2023-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_clip_visibility_alter_clip_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='uuid',
            field=models.CharField(default='beebb6af0da54e628d33213efe283f3c', max_length=200, unique=True),
        ),
    ]
