# Generated by Django 4.2.4 on 2023-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_alter_clip_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='uuid',
            field=models.CharField(default='d59a5c332b124d54ae5ce22e6b6dc923', max_length=200, unique=True),
        ),
    ]
