# Generated by Django 4.2.4 on 2023-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_alter_clip_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='uuid',
            field=models.CharField(default='13b7daf8515b4bd4a2c34cd88b65f581', max_length=200, unique=True),
        ),
    ]
